apiVersion: v2
name: rbac-server
description: The rbac-server integrates with dex and provides role-base access control.
home: https://llmariner.ai/
icon: https://raw.githubusercontent.com/llmariner/llmariner.github.io/refs/heads/main/assets/icons/logo.svg
type: application
version: 1.4.0
appVersion: 1.4.0
sources:
  - https://github.com/llmariner/rbac-manager
keywords:
  - llmariner
annotations:
  "artifacthub.io/category": ai-machine-learning
  "artifacthub.io/license": Apache-2.0
