apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbac-server.fullname" . }}-internal-grpc
  labels:
    {{- include "rbac-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.internalGrpcPort }}
    targetPort: internal-grpc
    protocol: TCP
    name: internal-grpc
  selector:
    {{- include "rbac-server.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbac-server.fullname" . }}-http
  labels:
    {{- include "rbac-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.monitoringPort }}
      targetPort: monitoring
      protocol: TCP
      name: monitoring
  selector:
    {{- include "rbac-server.selectorLabels" . | nindent 4 }}
